name: WanderingMarket
version: '${version}'
main: com.convallyria.wanderingmarket.WanderingMarket
api-version: 1.18
authors: [ SamB440 ]
description: A global trade system using a wandering market
website: https://www.convallyria.com
